import { v4 as uuidv4 } from "uuid";

export const lecturePartsTemplate = () => ({
  text: {
    id: uuidv4(),
    attributeType: "text",
    attributeTitle: "",
    attributeText: "",
    hided: false,
  },
  present: {
    id: uuidv4(),
    attributeType: "present",
    attributeTitle: "",
    attributeText: "",
    hided: false,
    fileName: "",
    fileSize: 0,
    filePath: "",
    downloadAllowed: false,
  },
  audio: {
    id: uuidv4(),
    attributeType: "audio",
    attributeTitle: "",
    attributeText: "",
    hided: false,
    fileName: "",
    fileSize: 0,
    filePath: "",
    downloadAllowed: false,
  },
  video: {
    id: uuidv4(),
    attributeType: "video",
    attributeTitle: "",
    attributeText: "",
    hided: false,
    fileName: "",
    fileSize: 0,
    filePath: "",
    downloadAllowed: false,
  },
  picture: {
    id: uuidv4(),
    attributeType: "picture",
    attributeTitle: "",
    attributeText: "",
    hided: false,
    attributeImages: [],
  },
  file: {
    id: uuidv4(),
    attributeType: "file",
    attributeTitle: "",
    attributeText: "",
    hided: false,
    attributeFiles: [],
  },
  link: {
    id: uuidv4(),
    attributeType: "link",
    attributeTitle: "",
    attributeText: "",
    hided: false,
    attributeLinks: [],
  },
  homework: {
    id: uuidv4(),
    attributeType: "homework",
    attributeTitle: "",
    attributeText: "",
    hided: false,
    attributeFiles: [],
    attributeLinks: [],
  },
});
